name: Release resource

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - name: Install Dependencies
        run: |
          npm install
      - name: Build project
        run: |
          npm run build
      - name: Release Project
        run: |
          npm run release
        env:
          ZEIT_TOKEN: ${{ secrets.Now }}
